/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2021-05-16 16:02:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web_002dpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import controller.User_Controller;
import controller.UserRegistration_Controller;
import utility.HTMLUtility;
import java.util.HashMap;
import utility.ServletUtility;
import utility.DataUtility;
import controller.Login_Controller;
import controller.ORSView;

public final class User_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("utility.HTMLUtility");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("controller.User_Controller");
    _jspx_imports_classes.add("utility.ServletUtility");
    _jspx_imports_classes.add("controller.UserRegistration_Controller");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("controller.Login_Controller");
    _jspx_imports_classes.add("controller.ORSView");
    _jspx_imports_classes.add("utility.DataUtility");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- StyleSheet Link -->\r\n");
      out.write("<link href=\"");
      out.print(ORSView.STYLESHEET);
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      dto.UserDTO dto = null;
      dto = (dto.UserDTO) _jspx_page_context.getAttribute("dto", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (dto == null){
        dto = new dto.UserDTO();
        _jspx_page_context.setAttribute("dto", dto, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List roleList = (List) request.getAttribute("roleList");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String fName = null;
	String lName = null;

	if (dto != null && dto.getName() != null) {
		String fnlName = DataUtility.getStringData(dto.getName());
		String[] Name = fnlName.split(" ", 2);

		fName = Name[0];
		lName = Name[1];
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\" id=\"container\">\r\n");
      out.write("\t\t<div id=\"header\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"ty-auto h-auto\" id=\"App_Body\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"login_backgound\" class=\"card\">\r\n");
      out.write("\t\t\t\t<div class=\"form-block text-white \">\r\n");
      out.write("\t\t\t\t\t<div class=\"text-center mt-5 mb-4 \">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							if (dto.getId() > 0) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h3>Update User</h3>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h3>Add User</h3>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							if (ServletUtility.getErrorMessage(request) != "") {
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alert alert-danger alert-dismissible fade show text-center\" role=\"alert\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(ServletUtility.getErrorMessage(request));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");

							}
							if (ServletUtility.getSuccessMessage(request) != "") {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alert alert-success alert-dismissible fade show text-center\" role=\"alert\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(ServletUtility.getSuccessMessage(request));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<form action=\"");
      out.print(ORSView.USER_CTL);
      out.write("\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group first text-white mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"username\">First Name</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"firstName\" type=\"text\" class=\"form-control\" placeholder=\"Enter First Name\" id=\"firstname\" value=\"");
      out.print(DataUtility.getStringData(fName));
      out.write("\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"color: red;\">");
      out.print(ServletUtility.getMessage("firstName", request));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group first text-white mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"username\">Last Name</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"lastName\" type=\"text\" class=\"form-control\" placeholder=\"Enter Last Name\" id=\"lastname\" value=\"");
      out.print(DataUtility.getStringData(lName));
      out.write("\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"color: red;\">");
      out.print(ServletUtility.getMessage("lastName", request));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group first text-white mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"username\">Login Id</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"login\" type=\"text\" class=\"form-control\" placeholder=\"Enter Login Id\" id=\"username\" value=\"");
      out.print(DataUtility.getStringData(dto.getLogin()));
      out.write("\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"color: red;\">");
      out.print(ServletUtility.getMessage("login", request));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group last mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"password\">Password</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"password\" type=\"password\" class=\"form-control\" placeholder=\"Enter Password\" id=\"password\" value=\"");
      out.print(DataUtility.getStringData(dto.getPassword()));
      out.write("\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"color: red;\">");
      out.print(ServletUtility.getMessage("password", request));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group last mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"password\">Confirm Password</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"confirmPassword\" type=\"password\" class=\"form-control\" placeholder=\"Confirm Password\" id=\"confirmPassword\" value=\"");
      out.print(DataUtility.getStringData(dto.getPassword()));
      out.write("\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"color: red;\">");
      out.print(ServletUtility.getMessage("password", request));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group last mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"password\">Gender </label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								HashMap<String, String> map = new HashMap<String, String>();
								map.put("Male", "Male");
								map.put("Female", "Female");

								String htmlList = HTMLUtility.getList("gender", dto.getGender(), map);
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"form-group last mb-0\">");
      out.print(htmlList);
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"color: red;\">");
      out.print(ServletUtility.getMessage("gender", request));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group last mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"dob\">Date of Birth</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"dob\" type=\"text\" class=\"form-control \" placeholder=\"dd/mm/yyyy\" id=\"datepicker1\" value=\"");
      out.print(DataUtility.getDateString(dto.getDob()));
      out.write("\" readonly=\"readonly\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"color: red;\">");
      out.print(ServletUtility.getMessage("dob", request));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group first text-white mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"mobile\">Mobile No.</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"mobileNo\" maxlength=\"10\" type=\"text\" class=\"form-control\" placeholder=\"Enter Mobile Number\" id=\"mobileNo\" value=\"");
      out.print(DataUtility.getStringData(dto.getMobileNo()));
      out.write("\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"color: red;\">");
      out.print(ServletUtility.getMessage("mobileNo", request));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group last mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"password\">Role </label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								String roleDrop = HTMLUtility.getList("roleId", String.valueOf(dto.getRoleId()), roleList);
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"form-group last mb-0\">");
      out.print(roleDrop);
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"color: red;\">");
      out.print(ServletUtility.getMessage("roleId", request));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Hidden Fields -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"id\" value=\"");
      out.print(dto.getId());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"createdBy\" value=\"");
      out.print(dto.getCreatedBy());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"modifiedBy\" value=\"");
      out.print(dto.getModifiedBy());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"createdDatetime\" value=\"");
      out.print(dto.getCreatedDatetime());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"modifiedDatetime\" value=\"");
      out.print(dto.getModifiedDatetime());
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							if (dto.getId() > 0) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mx-auto my-2 flex-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-outline-primary btn-block my-4 mx-3\" name=\"operation\" value=\"");
      out.print(User_Controller.OP_SAVE);
      out.write("\">Update</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-outline-light btn-block my-4 mx-3\" name=\"operation\" value=\"");
      out.print(User_Controller.OP_CANCEL);
      out.write("\">Cancel</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mx-auto my-2 flex-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-outline-primary btn-block my-4 mx-3\" name=\"operation\" value=\"");
      out.print(User_Controller.OP_SAVE);
      out.write("\">Add</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"reset\" class=\"btn btn-outline-light btn-block my-4 mx-3\" name=\"operation\" value=\"Reset\">Reset</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"footer\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
